"""Modified Text, URL to path.

Revision ID: 1a5b96dc6e5d
Revises: 6c962be59e9d
Create Date: 2020-03-24 11:31:00.213109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a5b96dc6e5d'
down_revision = '6c962be59e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Text', 'storage_url', new_column_name='storage_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Text', 'storage_path', new_column_name='storage_url')
    # ### end Alembic commands ###
