"""Adding Text table.

Revision ID: 6c962be59e9d
Revises: aad90282b4f2
Create Date: 2020-03-23 19:55:21.067994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c962be59e9d'
down_revision = 'aad90282b4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=512), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['URL.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Text')
    # ### end Alembic commands ###
